### ISSUE TITLE
Exceptions to "Protagonist can die" tweak?

### ISSUE THREAD

**Issue by agb1** [K4thos/EET_Tweaks#3]
Roxanne's Return to Faerun mod is designed around the concept that protagonist death ends the game, but Return to Faerun only starts after the end of ToB.  Is there a simple global that RtF can set to disable this tweak?

**Comment by whiteagnus** [comment]
Hmm, there is no global to disable this tweak, because EET uses the "Player 1 can die" flag in the area (I think currently only available in BG2:EE and IWD:EE)
We could add an arealist with the RtF areas, to not patch this files, or the component could be installed before RtF and the areas wouldn't be patched...

**Comment by agb1** [comment]
We can use installation order for BWS and make a note in the RtF mod about this.  Thanks.
